version: "3"

includes:
  utils: "tools/yscope-dev-utils/taskfiles/utils.yml"

vars:
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"
  G_EMSDK_DIR: "{{.G_BUILD_DIR}}/emsdk"
  G_WSAM_BUILD_DIR: "{{.G_BUILD_DIR}}/wasm"

tasks:
  default:
    deps: ["wasm"]

  clean:
    cmds:
      - task: "clean-emsdk"
      - task: "clean-wasm"
      - "rm -rf '{{.G_BUILD_DIR}}'"

  clean-emsdk:
    cmds:
      - "rm -rf '{{.G_EMSDK_DIR}}'"

  clean-wasm:
    cmds:
      - "rm -rf '{{.G_WSAM_BUILD_DIR}}'"

  emsdk:
    vars:
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.TASK}}.md5"
      OUTPUT_DIR: "{{.G_EMSDK_DIR}}"
    sources: ["{{.TASKFILE}}"]
    generates: ["{{.CHECKSUM_FILE}}"]
    deps:
      - "init"
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          DATA_DIR: "{{.OUTPUT_DIR}}"
    cmds:
      - task: "clean-emsdk"
      - "git clone 'https://github.com/emscripten-core/emsdk.git' '{{.G_EMSDK_DIR}}'"
      - |-
        cd "{{.G_EMSDK_DIR}}"
        ./emsdk install latest
        ./emsdk activate latest
      # This command must be last
      - task: "utils:compute-checksum"
        vars:
          DATA_DIR: "{{.OUTPUT_DIR}}"
          OUTPUT_FILE: "{{.CHECKSUM_FILE}}"

  wasm:
    vars:
      CHECKSUM_FILE: "{{.G_BUILD_DIR}}/{{.TASK}}.md5"
      OUTPUT_DIR: "{{.G_WSAM_BUILD_DIR}}"
    sources:
      - "{{.TASKFILE}}"
      - "CMakeLists.txt"
      - "src/**/*"
    generates: ["{{.CHECKSUM_FILE}}"]
    deps:
      - "emsdk"
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          DATA_DIR: "{{.OUTPUT_DIR}}"
    cmds:
      - task: "clean-wasm"
      - "mkdir '{{.OUTPUT_DIR}}'"
      - |-
        cmake -S "{{.ROOT_DIR}}" -B "{{.OUTPUT_DIR}}" -G "Unix Makefiles"
        cmake --build "{{.OUTPUT_DIR}}" --parallel
      # This command must be last
      - task: "utils:compute-checksum"
        vars:
          DATA_DIR: "{{.OUTPUT_DIR}}"
          OUTPUT_FILE: "{{.CHECKSUM_FILE}}"

  init:
    internal: true
    silent: true
    run: "once"
    cmds:
      - "mkdir -p '{{.G_BUILD_DIR}}'"
